version: '3.8'

services:
  app:
    image: dstdcie17/file-service:latest
    container_name: file-Service-container
    restart: unless-stopped
    ports:
      - '5549:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000

      # CORS - IMPORTANT: Remplacez par vos domaines autorisés
      - CORS_ORIGINS=*

      # Redis local sans authentification
      - REDIS_HOST=redis
      - REDIS_PORT=6379

      # Supabase
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxYXpvYWx1cWFybnFhdXVlbnl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3NjM2MjEsImV4cCI6MjA3ODMzOTYyMX0.g4o4MyiMxeHAsC2pSdVSy0HFhnNO2r3BJAt4G5ozxM8
      - SUPABASE_ROLE_SERVICE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxYXpvYWx1cWFybnFhdXVlbnl2Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2Mjc2MzYyMSwiZXhwIjoyMDc4MzM5NjIxfQ.XuqkbTHgYa0R77QQIbuhCjb6NLglVbb2AZ_3vz0IMuM
      - SUPABASE_URL=https://rqazoaluqarnqauuenyv.supabase.co

      # Bucket
      - DEFAULT_BUCKET=api-buckets

      # Admin par défaut
      - DEFAULT_ADMIN_USERNAME=File-System
      - DEFAULT_ADMIN_PASSWORD=SDIVD2025

    depends_on:
      redis:
        condition: service_healthy
    networks:
      - file-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis/redis-stack-server:latest
    container_name: file-redis-container
    restart: unless-stopped
    ports:
      - '6381:6379'
    volumes:
      - redis_data:/data
    networks:
      - file-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:

networks:
  file-network:
    driver: bridge
